#!/bin/bash

if [[ -z "$1" ]]
then
	echo -e "\t\tNo Argument Given\n"
	printf '%s\n' "$usage"
elif [[ $1 = "cpu" ]] && [[ $2 = "getinfo" ]]
then
	exec lscpu
elif [[ $1 = "memory" ]] && [[ $2 = "getinfo" ]]
then
	exec free
elif [[ $1 = "user" ]] && [[ $2 = "create" ]]
then
	source create
	#exec sudo adduser myuser --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
	#exec sudo useradd -s /bin/bash -m -p toor myuser

elif [[ $1 = "user" ]] && [[ $2 = "list" ]]
then
	source list
	#. ./list

elif [[ $1 = "file" ]] && [[ $2 = "getinfo" ]]
then
	source information

else
	echo "bad input"
fi