#!/bin/bash

# to check if root user [as without root it gives error: cannot lock /etc/passwd]
#That's because we don't have permissions for those operations
#You can't read /etc/shadow
#You can't directly modify /etc/passwd

if [[ -n $3 ]]
then
	if [[ $(id -u) -eq 0 ]]
	then
		read -r -s -p "Enter password : " password
		grep -E "^$3" /etc/passwd >/dev/null
			if [[ $? -eq 0 ]]
			then
				echo -e "\n$3 exists!"
				exit 1
			else
				pass=$(perl -e 'print crypt($ARGV[0], "password")' "$password")
				useradd -s /bin/bash -m -p "$pass" "$3"
				[ $? -eq 0 ] && echo "User has been added to system!" || echo "Failed to add a user!"
			fi
	else
		echo "Only root may add a user to the system."
		exit 2
	fi
else
	echo "Write Username also"
fi


#sudo useradd $username
#echo $username:U6aMy0wojraho | sudo chpasswd -e
#su $username
