#!/bin/bash

if [[ -n $3 ]] && [[ -e $3 ]] && [[ -z $4 ]]
then
	echo -n "File: " ; ls -l "$3" | awk '{print$9}' #stat -c '%n' $3
	echo -n "Access: " ; ls -l "$3" | awk '{print$1}' #stat -c '%A' $3
	echo -n "Size(B): " ; ls -l "$3" | awk '{print$5}' #stat -c '%s' $3
	echo -n "Owner: " ; ls -l "$3" | awk '{print$4}' #stat -c '%U' $3
	echo -n "Modify: " ; stat -c '%y' "$3"

elif [[ -e $4 ]]
then
	case $3 in
	-s | --size )
		echo -n "Size(B): " ; ls -l "$4" | awk '{print$5}'
		;;
	-p | --permissions )
		echo -n "Access: " ; ls -l "$4" | awk '{print$1}'
		;;
	-o | --owner )
		echo -n "Owner: " ; ls -l "$4" | awk '{print$4}'
		;;
	-m | --last-modified )
		echo -n "Modify: " ; stat -c '%y' "$4"
		;;
	*)
		echo "Wrong option"
	esac

else
	echo "File not present..!"
fi