#!/bin/bash

version="internsctl v0.1.0"

usage="Usage: $0 [ARGUMENT]...[OPTION]...


	Mandatory arguments [with options]
		cpu getinfo		output cpu information of server
		memory getinfo		output memory information of server
		file getinfo [FILENAME]	output file information
		user create		create a new user on server
		user list		list all users on server
		--help			display this help and exit
		--version		display version information and exit"


if [[ -z "$1" ]] #&& [[ -z "$2" ]]
then
	echo "no input"
elif [[ $1 = "cpu" ]] && [[ $2 = "getinfo" ]]
then
	source cpu
elif [[ $1 = "memory" ]] && [[ $2 = "getinfo" ]]
then
	source memory
elif [[ $1 = "user" ]] && [[ $2 = "create" ]]
then
	source create
	#exec sudo adduser myuser --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
	#exec sudo useradd -s /bin/bash -m -p toor myuser

elif [[ $1 = "user" ]] && [[ $2 = "list" ]] && [[ -z "$3" ]]
then
	source list
	#. ./list
elif [[ $1 = "user" ]] && [[ $2 = "list" ]] && [[ $3 = "--sudo-only" ]]
then
	source sudoer
elif [[ $1 = "file" ]] && [[ $2 = "getinfo" ]] && [[ -z $4 ]]
then
	source information

elif [[ $1 = "file" ]] && [[ $2 = "getinfo" ]] && [[ -e $4 ]] # -e checks if file exit
then
	source information2

elif [[ $1 = "--help" ]]
then
	printf '%s\n' "$usage"
elif [[ $1 = "--version" ]]
then
	printf '%s\n' "$version"
else
	echo "bad input"
fi
